apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: exposed-app
data:
  nginx.conf: |
    user root;
    events {}
    
    http {
        include  mime.types;
        server {
            listen 80;
            server_name localhost;
        
            location ^~ /app1 {
              alias   /apps/app1/dist/spa;
              index index.html index.htm index.html;
              try_files $uri $uri/ /app1/index.html;
            }

              location ^~ /app2 {
              alias   /apps/app2/dist/spa;
              index index index.html index.htm;
              try_files $uri $uri/ /app2/index.html;
            }
            

        }
    }

          
