apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: exposed-app
data:
  nginx.conf: |
    events {}
    
    http {
        include  mime.types;
        server {
            listen 80;
            server_name localhost;

            root /apps/app1/dist/spa;
            index          index.html;
            try_files $uri $uri/ /index.html =404;

        }
    }

          
