apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: exposed-app
data:
  nginx.conf: |
    events {}
      
      http {
        include    mime.types;

      server {
        listen 80;
        server_name localhost;

        location ^~ /app1 {
          proxy_pass http://app1-svc.exposed-app.svc.cluster.local;
          rewrite ^/app1/(.*)$ /$1 break;
        }


        location ^~ /app2 {
          proxy_pass http://app2-svc.exposed-app.svc.cluster.local;
          rewrite ^/app2/(.*)$ /$1 break;
        }

      }
    }
            
